source 'https://rubygems.org'

# To run the tests you should only need obvious and validation
gem 'obvious'
gem 'validation'

# The gems below are needed for the web app and various database plugs
# gem 'sinatra'
# gem 'slim'
# gem 'sequel'
# gem 'mysql'
# gem 'moped'
# gem 'rest-client'

group :development do
  gem 'rspec'
  gem 'shotgun'
  gem 'thin'
  gem 'guard-rspec'
  gem 'rb-fsevent', require: false
end